version: "3.8"
services:
  db:
    build: db/
    container_name: "mongodb"
    ports:
    - 27017
  api:
    build: api/
    container_name: "fastapi"
    ports:
    - "80:80"
    depends_on:
      - db